### ISSUE TITLE
Nav and billboard

### ISSUE THREAD

**Issue by annamisak** [malo0140/portfolio#2]
Your page was tested on mobile and these issues were detected:

-Your navigation overflows the blue nav box.
-Billboard/Cover image is only showing on half of the page width
-Social icons are too small

**Comment by shelbyboyd** [comment]
same issue in android internet explorer

**Comment by marisabivi** [comment]
Same in Opera Mini.

**Comment by benmarley** [comment]
windows 8 mobile same issues, social media button could use more space as well
